# Generated by Django 3.0.1 on 2020-04-24 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='color',
            field=models.CharField(choices=[('none', 'None'), ('black', 'Black'), ('white', 'White')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='size',
            field=models.CharField(choices=[('N', 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='N', max_length=4),
        ),
        migrations.AlterField(
            model_name='basket',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.Coupon'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
