# Generated by Django 3.0.1 on 2020-04-25 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0002_auto_20200424_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'basket', 'verbose_name_plural': 'baskets'},
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'basket item', 'verbose_name_plural': 'basket items'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL),
        ),
    ]
