# Generated by Django 3.0.1 on 2020-05-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20200426_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='size',
        ),
    ]
